TEL-4722 Ensures users have to explicitly enable production (#171)
What did we do?
--

1. Ensured you have to explicitly enable production
2. Adds documentation for local testing of `alert-config-builder` + `alert-config` changes
3. Forces overriding of `AlertConfig.environmentConfig` so that if you don't specify and envs, it will crash

References
--

https://jira.tools.tax.service.gov.uk/browse/TEL-4722

Evidence of work
--

1. Gimmicked local `alert-config` to use this branch
2. Generated services.yml locally with old and new versions of alert-config-builder
3. **Asserted that** where no environment config was present, the builder crashed:
```
[error] /Users/gavin/Code/telemetry/alert-config/src/main/scala/uk/gov/hmrc/alertconfig/configs/DASSSDLTFiling.scala:11:8: object creation impossible.
[error] Missing implementation for member of trait AlertConfig:
[error]   def environmentConfig: Seq[uk.gov.hmrc.alertconfig.builder.EnvironmentAlertBuilder] = ???
[error] object DASSSDLTFiling extends AlertConfig {
[error]        ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
```
4. Resolve these errors and ran alert-config with local build of alert-config-builder
5. Diff'd the results
6. **Asserted that** it does not differ EXCEPT where the existing code is erroneous

> We noted a number of instances whereby users had small misconfigurations, such as:
> 
> ![image](https://github.com/user-attachments/assets/4618ce95-83fd-4a19-a1b4-d7df29007692)
> 
> These were resolved in  https://github.com/hmrc/alert-config/pull/3808

*Finding these faults also proves the value of this change* :-) 

The only difference in production services.yml between that generated right now and the updated version is a single CIP error, which the new version fixes:

<img width="858" alt="image" src="https://github.com/user-attachments/assets/86e0496a-c41d-4286-8e25-0743666322dc">

services.yml deltas for all envs : 

Env | Diff result
-- | --
Production | ✅ New version fixes a problem with a CIP alert
Externaltest | ✅ No-op
Staging | ✅ New version fixes a problem in `DASSPortalAPIAndDBTest`
QA | ✅ No-op
Development | ✅ No-op
Integration | ✅ No-op

Next Steps
--

1. Update alert-config repo PR https://github.com/hmrc/alert-config/pull/3807 with the necessary changes. _That PR is currently broken, waiting for this to be merged, but you can see the changes I propose therein_

Risks
--

1. This is a very large change. We have to be careful not to change alert behaviour
    a. My testing will catch all such errors in production by diff'ing the generated `services.yml` to that built with existing alert-config-builder.
2. Do we need to do anything for custom alerts at this time?

Collaboration
--

Co-authored by: @ma3574 Muhammed Ahmed <ma3574@users.noreply.github.com>
Co-authored by: @alextcap <alex.tasioulis@users.noreply.github.com>